# Generated by Django 4.2 on 2024-01-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_topic_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.IntegerField(null=True),
        ),
    ]
